[versions]
agp = "8.9.2"
firebaseBom = "34.9.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.2.1"
workRuntime = "2.9.0"
coil = "2.5.0"
mpandroidchart = "v3.1.0"
playserviceauth = "20.7.0"
googleapiservicesdrive = "v3-rev20230822-2.0.0"
googleapiclientandroid = "2.2.0"
zxingcore = "3.5.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntime" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
playserviceauth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playserviceauth" }
googleapiservicesdrive = { group = "com.google.apis", name = "google-api-services-drive", version.ref = "googleapiservicesdrive" }
googleapiclientandroid = { group = "com.google.api-client", name = "google-api-client-android", version.ref = "googleapiclientandroid" }
zxingcore = { group = "com.google.zxing", name = "core", version.ref = "zxingcore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

